[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gen-pd"
path = "src/predecessor.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clap = { version = "4.3.10", features = ["derive"] }
